#!/bin/bash

# tagging
notmuch tag -inbox -unread -new -touched +trash -deleted -- folder:/Trash/
notmuch tag -inbox -unread -new -touched +spam -- folder:/Spam/
notmuch tag -inbox -unread -new +sent -draft -- \(folder:/Sent/ or folder:/sent/\)
notmuch tag -inbox -unread -new +draft -- folder:/Draft/

# mailers
notmuch tag -inbox -new +newsletter +quora -- from:/@quora.com/ and tag:new
notmuch tag -inbox -new +shopping +amazon -- from:/@amazon.in/ and tag:new
notmuch tag -inbox -new +bankalerts +hdfc -- from:alerts@hdfcbank.net and tag:new
notmuch tag -inbox -new +bankalerts +niyox -- from:esfb-alerts@equitasbank.com and tag:new
notmuch tag -inbox -new +newsletter +niyox -- from:campaigns@equitasbank.com and tag:new
notmuch tag -inbox -new +newsletter +academia -- from:updates@academia-mail.com and tag:new
notmuch tag -inbox -new +bankalerts +twino -- from:info@twinoinvest.eu and tag:new
notmuch tag -inbox -new +newsletter +navi +mf -- from mf@navi.com and tag:new
notmuch tag -inbox -new +newsletter +ebay -- from ebay@reply1.ebay.com and tag:new
notmuch tag -inbox -new +newsletter +researcher -- from:team@email.researcher-app.com and tag:new
notmuch tag -inbox -new +newsletter +twitter -- \(from:notify@twitter.com or from:info@twitter.com\) and tag:new
notmuch tag -inbox -new +newsletter +jio -- from:info@mailer.jio.com and tag:new
notmuch tag -inbox -new +newsletter +rg -- from:no-reply@researchgatemail.net and 'subject:"/published an article/"' and tag:new
notmuch tag -inbox -new +newsletter +mf -- from:info@axismf.com and tag:new
notmuch tag -inbox -new +newsletter +mf -- from:info@kotak-amc.com and tag:new
notmuch tag -inbox -new +newsletter +ieee -- from:ieee-spectrum@deliver.ieee.org and tag:new
notmuch tag -inbox -new +newsletter -- from:info@meercode.io and tag:new
notmuch tag -inbox -new +newsletter -- from:monday.reply@brighttalk.com and tag:new
notmuch tag -inbox -new +newsletter -- from:webinars@devops.com and tag:new
notmuch tag -inbox -new +newsletter -- from:products@emailers.idfcmf.com and tag:new
notmuch tag -inbox -new +newsletter -- from:customerservice@ack-media.com and tag:new
notmuch tag -inbox -new +newsletter -- from:noreply@content.goibibo.com and tag:new
notmuch tag -inbox -new +newsletter -- from:hermes.reply@brighttalk.com and tag:new
notmuch tag -inbox -new +newsletter -- from:analysts@techstrongresearch.com and tag:new
notmuch tag -inbox -new +newsletter -- from:events@techstronggroup.com and tag:new
notmuch tag -inbox -new +newsletter -- from:flickrteam@arrow.flickr.com and tag:new
notmuch tag -inbox -new +newsletter -- from:irctctourismoffers@irctc.co.in and tag:new
notmuch tag -inbox -new +newsletter -- from:mfservice@motilaloswal.com and "body:'/To opt out from our newsletter/'" and tag:new
notmuch tag -inbox -new +newsletter -- from:mfmarketing@invesco.com and "body:'/from this newsletter/'" and tag:new
notmuch tag -inbox -new +newsletter +msfamily -- from:familysafety@microsoft.com and 'subject:"/Weekly activity report/"' and tag:new
notmuch tag -inbox -new +newsletter -- from:aws-marketing-email-replies@amazon.com and tag:new
notmuch tag -inbox -new +newsletter -- from:Newsletter@email.elitedangerous.com and tag:new
notmuch tag -inbox -new +newsletter -- from:noreply-local-guides@google.com and subject:/Newsletter/ and tag:new
notmuch tag -inbox -new +newsletter -- from:info@service.icicipruamc.com and "body:'/unsubscribe from this newsletter/'" and tag:new
notmuch tag -inbox -new +newsletter -- from:Noreply@e.crm.lego.com and tag:new
notmuch tag -inbox -new +newsletter -- from:noreply@paytmoffers.in and tag:new
notmuch tag -inbox -new +newsletter -- from:noreply@mailer.abhibus.com and tag:new
notmuch tag -inbox -new +newsletter -- from:investments@goniyo.com and "subject:'/Invest the change Weekly Summary/'" and tag:new
notmuch tag -inbox -new +newsletter -- from:ebay@reply.ebay.com and body:/Newsletter/ and tag:new

# otp marking
notmuch tag +otp -- from:/bank/ and subject:/OTP/ and tag:new
notmuch tag +otp -- from:/microsoft.com/ and "subject:'/single-use code/'" and tag:new

# direct to trash stuff
notmuch tag -inbox -new +newsletter +trash -- from:premium@academia-mail.com and tag:new
notmuch tag -inbox -new +trash -- from:scholarcitations-noreply@google.com and 'subject:"/Time to update your articles/"' and tag:new
notmuch tag -inbox -new +trash -- from:billing@mitsu.in and tag:new
notmuch tag -inbox -new +trash -- from:familysafety@microsoft.com and 'subject:"/have more screen time/"' and tag:new
notmuch tag -inbox -new +trash -- from:no-reply@researchgatemai and 'subject:"Soren, people are reading your work"' and tag:new


# tag inbox (for those in inbox)
notmuch tag +inbox -- folder:/INBOX/ and tag:new

# auto-delete rules
notmuch tag +trash -- tag:newsletter and date:..3-months-ago
notmuch tag +trash -inbox -- tag:otp and date:..2-hours-ago

# origins
notmuch tag +svu -- from:sorend@cs.svu-ac.in or to:sorend@cs.svu-ac.in and tag:new
notmuch tag +sadcom -- from:soren@atmakuridavidsen.com or to:soren@atmakuridavidsen.com and tag:new
notmuch tag +corp -- from:soren@hamisoke.com or to:soren@hamisoke.com and tag:new

# finished
notmuch tag -new -- tag:new

# -*- mode: shell-script -*-
