#!/bin/bash

TRASH_FOLDER=ad/Trash
TRASH_PATH=$HOME/Mail/$TRASH_FOLDER/cur/

# gmail handle deleted -> trash
notmuch tag -deleted -inbox +trash -- folder:mail and tag:deleted

# other deleted -> zoho   (three steps, tag as deleting, move files, and untag deleting + tag trash)
# notmuch tag +deleting -- $(notmuch search --output threads \(tag:deleting or tag:deleted\) and -folder:mail)
# notmuch search --format=text0 --output=files -folder:mail and tag:deleting | xargs -0 -n1 -I {} mv "{}" $TRASH_PATH
# notmuch tag -deleting +trash -- tag:deleting or folder:$TRASH_FOLDER

# sync gmail
( cd $HOME/Mail/ && gmi sync )

# sync other imap
mbsync -a -c $HOME/.config/mbsync/mbsync.conf

# -*- mode: shell-script -*-
