name: make-check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  make-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Emacs
        run: |
          sudo apt-get update
          sudo apt-get install -y emacs-nox

      - name: Run make check
        run: make check
